services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: brenoleiriaoneto
      POSTGRES_PASSWORD: psql
      POSTGRES_DB: devconnect_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/devconnect_db
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    
volumes:
  pgdata:
  mongodata:

